#version 450
layout(local_size_x = 64) in;

layout(push_constant) uniform PC {
    int i0, i1, i2, i3, i4, i5, i6, i7;
    float f0, f1, f2, f3;
} pc;

layout(std430, binding = 0) readonly buffer ABuf { float A[]; };
layout(std430, binding = 1) readonly buffer BBuf { float B[]; };
layout(std430, binding = 2) buffer YBuf { float Y[]; };

void main() {
    uint stride = gl_NumWorkGroups.x * 64u;
    uint i = gl_GlobalInvocationID.y * stride + gl_GlobalInvocationID.x;
    if (i >= uint(pc.i0)) return;
    Y[i] = A[i] + B[i];
}
